name: Hardcore
author: Darrionat
main: me.darrionat.hardcore.Hardcore
description: Create a hardcore-mode server
version: 0.2
api-version: 1.13

permissions:
  hardcore.admin:
    description: Allows use of all commands
    default: op